# Generated by Django 3.2.7 on 2021-10-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=6)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clipboard.clipboard')),
            ],
        ),
    ]
