# Generated by Django 3.2.7 on 2021-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0002_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='link',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
